# Generated by Django 3.2.10 on 2021-12-18 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Путь до фото'),
            preserve_default=False,
        ),
    ]
