# Generated by Django 3.2.10 on 2021-12-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
