# Generated by Django 3.2.10 on 2021-12-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Итого'),
        ),
    ]
