# Generated by Django 3.2.10 on 2021-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_basket_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total',
        ),
    ]
