# Generated by Django 3.2.10 on 2021-12-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_basket_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('delivery', models.CharField(max_length=50, verbose_name='Способ доставки')),
                ('total_sum', models.IntegerField(verbose_name='Итоговая сумма')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.basket')),
            ],
        ),
    ]
