# Generated by Django 3.2.10 on 2021-12-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ManyToManyField(to='main.Basket'),
        ),
    ]
